/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoteste;
import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
   
    public void testeMedia(){
        int nota1, nota2, nota3;
        nota1 = 8;
        nota2 = 6;
        nota3 = 7;
        int media = (nota1+nota2+nota3)/3;
        System.out.println("A media eh: " + media);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String pegaString = StringUtils.upperCase(String.join(" ", args));
        System.out.println(pegaString);
        new App().testeMedia();
       
    }
}
