/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoteste;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void Testemedia(){
        App media1 = new App();
        System.out.println(media1);
    }
}
